export const MOCK_SHOE_CLEANING = [
  { id: 'sc-1', name: 'Normal/Canvas/Net/Non leather/Sports shoes', priceMinor: 35000, priceType: 'fixed', unit: 'pair' },
  { id: 'sc-2', name: 'Leather sneakers', priceMinor: 45000, priceType: 'fixed', unit: 'pair' },
  { id: 'sc-3', name: 'Shoe cleaning Monthly Package (8 pair)', priceMinor: 210000, priceType: 'fixed', unit: 'package' }
];

export const MOCK_DRY_CLEANING = [
  // Men - Top wear
  { id: 'dc-m1', name: 'Men Shirt', priceMinor: 9000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-m2', name: 'Men T-shirt', priceMinor: 9000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-m3', name: 'Men Sleeveless Shirt', priceMinor: 9000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-m4', name: 'Men Sweatshirt', priceMinor: 15000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-m5', name: 'Men Hoodie', priceMinor: 18000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-m6', name: 'Men Jacket (Leather)', priceMinor: 35000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-m7', name: 'Men Jacket (Bomber)', priceMinor: 25000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-m8', name: 'Men Jacket (Varsity)', priceMinor: 35000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-m9', name: 'Men Jacket (Sports)', priceMinor: 21000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-m10', name: 'Men Jacket (Nehru)', priceMinor: 15000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-m11', name: 'Men Jacket (Pathani Band Gala)', priceMinor: 45000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-m12', name: 'Men Tuxedo Jacket', priceMinor: 45000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-m13', name: 'Men Denim jacket', priceMinor: 18000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-m14', name: 'Men Winter Jacket', priceMinor: 35000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-m15', name: 'Men Long Jacket/Trench Coat', priceMinor: 35000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-m16', name: 'Men Biker jacket (Heavy with pads)', priceMinor: 55000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-m17', name: 'Men Shacket', priceMinor: 25000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-m18', name: 'Men Blazer', priceMinor: 25000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-m19', name: 'Men Waist coat', priceMinor: 15000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-m20', name: 'Men Flannel shirts', priceMinor: 18000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-m21', name: 'Men Sherwani (Light)', priceMinor: 35000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-m22', name: 'Men Sherwani (Heavy)', priceMinor: 45000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-m23', name: 'Men Sherwani (Groom)', priceMinor: 65000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-m24', name: 'Men Kurta (Light/Plain)', priceMinor: 18000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-m25', name: 'Men Kurta (Heavy/Embroidered)', priceMinor: 27000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-m26', name: 'Men Safari suit (Shirt only)', priceMinor: 9000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-m27', name: 'Men Indo-western top (Light)', priceMinor: 35000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-m28', name: 'Men Indo-western top (Heavy)', priceMinor: 45000, priceType: 'fixed', unit: 'piece' },

  // Men - Bottom wear
  { id: 'dc-mb1', name: 'Men Pant', priceMinor: 9000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-mb2', name: 'Men Jeans', priceMinor: 9000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-mb3', name: 'Men Trousers', priceMinor: 9000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-mb4', name: 'Men Cargo Pants', priceMinor: 9000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-mb5', name: 'Men Pyjama (Light)', priceMinor: 18000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-mb6', name: 'Men Pyjama (Heavy/Embroidered)', priceMinor: 27000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-mb7', name: 'Men Chudidar (Light)', priceMinor: 18000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-mb8', name: 'Men Chudidar (Heavy)', priceMinor: 27000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-mb9', name: 'Men Lungi (Normal)', priceMinor: 13000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-mb10', name: 'Men Lungi (Pleated)', priceMinor: 18000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-mb11', name: 'Men Lower', priceMinor: 10000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-mb12', name: 'Men Half pant / Shorts', priceMinor: 6000, priceType: 'fixed', unit: 'piece' },

  // Women - Top wear
  { id: 'dc-w1', name: 'Women Top (Light)', priceMinor: 9000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-w2', name: 'Women Top (Heavy)', priceMinor: 18000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-w3', name: 'Women Long top (Light)', priceMinor: 15000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-w4', name: 'Women Long top (Heavy)', priceMinor: 25000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-w5', name: 'Women Shirt (Light)', priceMinor: 9000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-w6', name: 'Women Shirt (Heavy)', priceMinor: 18000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-w7', name: 'Women T-shirt', priceMinor: 9000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-w8', name: 'Women Sweatshirt', priceMinor: 15000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-w9', name: 'Women Hoodie', priceMinor: 18000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-w10', name: 'Women Jacket (Leather)', priceMinor: 35000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-w11', name: 'Women Jacket (Bomber)', priceMinor: 25000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-w12', name: 'Women Jacket (Varsity)', priceMinor: 35000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-w13', name: 'Women Jacket (Sports)', priceMinor: 21000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-w14', name: 'Women Denim jacket', priceMinor: 18000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-w15', name: 'Women Winter Jacket', priceMinor: 35000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-w16', name: 'Women Long Jacket/Trench coat', priceMinor: 35000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-w17', name: 'Women Biker jacket (Heavy with pads)', priceMinor: 55000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-w18', name: 'Women Kurti (Light)', priceMinor: 18000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-w19', name: 'Women Kurti (Heavy)', priceMinor: 25000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-w20', name: 'Women Long kurti (light)', priceMinor: 25000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-w21', name: 'Women Long Kurti (Heavy)', priceMinor: 33000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-w22', name: 'Women Anarkali Kurti (Light)', priceMinor: 25000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-w23', name: 'Women Anarkali Kurti (Heavy)', priceMinor: 35000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-w24', name: 'Women Saree (Light/Cotton)', priceMinor: 30000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-w25', name: 'Women Saree (Silk Light)', priceMinor: 40000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-w26', name: 'Women Saree (Silk Heavy)', priceMinor: 55000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-w27', name: 'Women Saree (Heavy/Embroidered)', priceMinor: 40000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-w28', name: 'Women Kanjivaram Saree', priceMinor: 40000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-w29', name: 'Women Dulhan saree', priceMinor: 45000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-w30', name: 'Women Saree Banarasi (Light)', priceMinor: 35000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-w31', name: 'Women Saree Banarasi (Heavy)', priceMinor: 45000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-w32', name: 'Women Dupatta (Light)', priceMinor: 8000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-w33', name: 'Women Dupatta (Heavy)', priceMinor: 18000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-w34', name: 'Women Blouse (Light)', priceMinor: 5000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-w35', name: 'Women Blouse (Heavy)', priceMinor: 12000, priceType: 'fixed', unit: 'piece' },

  // Women - Bottom wear
  { id: 'dc-wb1', name: 'Women Pant', priceMinor: 9000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-wb2', name: 'Women Jeans', priceMinor: 9000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-wb3', name: 'Women Trousers', priceMinor: 9000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-wb4', name: 'Women Cargo Pants', priceMinor: 9000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-wb5', name: 'Women Pyjama (Light)', priceMinor: 18000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-wb6', name: 'Women Pyjama (Heavy/Embroidered)', priceMinor: 27000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-wb7', name: 'Women Chudidar (Light)', priceMinor: 18000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-wb8', name: 'Women Chudidar (Heavy)', priceMinor: 27000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-wb9', name: 'Women Lower', priceMinor: 10000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-wb10', name: 'Women Half pant / Shorts', priceMinor: 6000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-wb11', name: 'Women Sharara (Light)', priceMinor: 18000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-wb12', name: 'Women Sharara (Heavy)', priceMinor: 27000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-wb13', name: 'Women Lehenga (Light)', priceMinor: 45000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-wb14', name: 'Women Lehenga (Heavy)', priceMinor: 65000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-wb15', name: 'Women Lehenga (Heavy Cane)', priceMinor: 81000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-wb16', name: 'Women Skirt (Light)', priceMinor: 18000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-wb17', name: 'Women Skirt (Heavy)', priceMinor: 27000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-wb18', name: 'Women Palazzo (Light)', priceMinor: 15000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-wb19', name: 'Women Palazzo (Heavy)', priceMinor: 27000, priceType: 'fixed', unit: 'piece' },

  // Dress
  { id: 'dc-d1', name: 'Western One piece (Light)', priceMinor: 18000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-d2', name: 'Western one piece (Heavy)', priceMinor: 35000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-d3', name: 'Gown (Light)', priceMinor: 25000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-d4', name: 'Gown (Heavy)', priceMinor: 45000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-d5', name: 'Jumpsuit', priceMinor: 27000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-d6', name: 'Co-ord set (Light)', priceMinor: 27000, priceType: 'fixed', unit: 'set' },
  { id: 'dc-d7', name: 'Co-ord set (Heavy)', priceMinor: 36000, priceType: 'fixed', unit: 'set' },

  // Household 
  { id: 'dc-h1', name: 'Curtains 4x4', priceMinor: 10000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-h2', name: 'Curtains 8x4/10x4 (Light)', priceMinor: 25000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-h3', name: 'Curtains 8x4/10x4 (Heavy)', priceMinor: 35000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-h4', name: 'Curtains 11x5 to 15x6 (Light)', priceMinor: 35000, priceMaxMinor: 60000, priceType: 'variable', unit: 'piece' },
  { id: 'dc-h5', name: 'Curtains 11x5 to 15x6 (Heavy)', priceMinor: 45000, priceMaxMinor: 70000, priceType: 'variable', unit: 'piece' },
  { id: 'dc-h6', name: 'Curtains 16x7 to 21x10 (Light)', priceMinor: 80000, priceMaxMinor: 150000, priceType: 'variable', unit: 'piece' },
  { id: 'dc-h7', name: 'Curtains 16x7 to 21x10 (Heavy)', priceMinor: 90000, priceMaxMinor: 160000, priceType: 'variable', unit: 'piece' },
  { id: 'dc-h8', name: 'Carpet/Rug', priceMinor: 3500, priceType: 'fixed', unit: 'sqft' },
  { id: 'dc-h9', name: 'Cushion (Small)', priceMinor: 3000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-h10', name: 'Cushion (Large)', priceMinor: 5000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-h11', name: 'Blinds 4x4', priceMinor: 28000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-h12', name: 'Blinds 8x4', priceMinor: 55000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-h13', name: 'Blinds 9x5 to 13x10', priceMinor: 85000, priceMaxMinor: 250000, priceType: 'variable', unit: 'piece' },
  { id: 'dc-h14', name: 'Sofa (Normal Cloth without cushion)', priceMinor: 25000, priceType: 'fixed', unit: 'seat' },
  { id: 'dc-h15', name: 'Sofa (Rexin/Leather without cushion)', priceMinor: 35000, priceType: 'fixed', unit: 'seat' },
  { id: 'dc-h16', name: 'Dining table chair (Light/Cloth)', priceMinor: 15000, priceType: 'fixed', unit: 'chair' },
  { id: 'dc-h17', name: 'Dining table chair (Heavy/Rexin/Leather)', priceMinor: 21000, priceType: 'fixed', unit: 'chair' },
  { id: 'dc-h18', name: 'Cushion chair', priceMinor: 15000, priceType: 'fixed', unit: 'chair' },
  { id: 'dc-h19', name: 'Dohard (Single bed)', priceMinor: 18000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-h20', name: 'Dohard (Double bed)', priceMinor: 30000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-h21', name: 'Blanket/Comforter/Quilt (Single bed)', priceMinor: 35000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-h22', name: 'Blanket/Comforter/Quilt (Double bed)', priceMinor: 55000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-h23', name: 'Mattress cover (Double bed)', priceMinor: 24000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-h24', name: 'Doormats (Small)', priceMinor: 13000, priceType: 'fixed', unit: 'piece' },
  { id: 'dc-h25', name: 'Doormats (Large)', priceMinor: 27000, priceType: 'fixed', unit: 'piece' }
];

export const MOCK_STEAM_PRESS = [
  // Men Top
  { id: 'sp-m1', name: 'Men Shirt', priceMinor: 1800, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-m2', name: 'Men T-shirt', priceMinor: 1800, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-m3', name: 'Men Sleeveless Shirt', priceMinor: 1800, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-m4', name: 'Men Sweatshirt', priceMinor: 3000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-m5', name: 'Men Hoodie', priceMinor: 5000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-m6', name: 'Men Jacket (Nehru)', priceMinor: 5000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-m7', name: 'Men Jacket (Pathani Band Gala)', priceMinor: 12000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-m8', name: 'Men Tuxedo Jacket (jacket only)', priceMinor: 15000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-m9', name: 'Men Blazer', priceMinor: 10000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-m10', name: 'Men Waist coat', priceMinor: 5000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-m11', name: 'Men Flannel shirts', priceMinor: 3000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-m12', name: 'Men Sherwani (Light)', priceMinor: 15000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-m13', name: 'Men Sherwani (Heavy)', priceMinor: 25000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-m14', name: 'Men Sherwani (Groom)', priceMinor: 35000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-m15', name: 'Men Kurta (Light/Plain)', priceMinor: 1800, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-m16', name: 'Men Kurta (Heavy/Embroidered)', priceMinor: 6000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-m17', name: 'Men Safari suit (Shirt only)', priceMinor: 3000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-m18', name: 'Men Indo-western top (Light)', priceMinor: 9000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-m19', name: 'Men Indo-western top (Heavy)', priceMinor: 18000, priceType: 'fixed', unit: 'piece' },

  // Men Bottom
  { id: 'sp-mb1', name: 'Men Pant', priceMinor: 1800, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-mb2', name: 'Men Jeans', priceMinor: 1800, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-mb3', name: 'Men Trousers', priceMinor: 1800, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-mb4', name: 'Men Cargo Pants', priceMinor: 1800, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-mb5', name: 'Men Pyjama (Light)', priceMinor: 1800, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-mb6', name: 'Men Pyjama (Heavy/Embroidered)', priceMinor: 5000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-mb7', name: 'Men Chudidar (Light)', priceMinor: 3000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-mb8', name: 'Men Chudidar (Heavy)', priceMinor: 5000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-mb9', name: 'Men Lungi (Normal)', priceMinor: 3000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-mb10', name: 'Men Lungi (Pleated)', priceMinor: 10000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-mb11', name: 'Men Lower', priceMinor: 1800, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-mb12', name: 'Men Half pant / Shorts', priceMinor: 1800, priceType: 'fixed', unit: 'piece' },

  // Women Top
  { id: 'sp-w1', name: 'Women Top (Light)', priceMinor: 1800, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-w2', name: 'Women Top (Heavy)', priceMinor: 4000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-w3', name: 'Women Long top (Light)', priceMinor: 4000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-w4', name: 'Women Long top (Heavy)', priceMinor: 6000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-w5', name: 'Women Shirt (Light)', priceMinor: 1800, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-w6', name: 'Women Shirt (Heavy)', priceMinor: 3000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-w7', name: 'Women T-shirt', priceMinor: 1800, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-w8', name: 'Women Sweatshirt', priceMinor: 3000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-w9', name: 'Women Hoodie', priceMinor: 5000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-w10', name: 'Women Over coat', priceMinor: 10000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-w11', name: 'Women Kurti (Light)', priceMinor: 3000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-w12', name: 'Women Kurti (Heavy)', priceMinor: 6000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-w13', name: 'Women Long kurti (light)', priceMinor: 5000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-w14', name: 'Women Long Kurti (Heavy)', priceMinor: 10000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-w15', name: 'Women Anarkali Kurti (Light)', priceMinor: 6000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-w16', name: 'Women Anarkali Kurti (Heavy)', priceMinor: 12000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-w17', name: 'Women Saree (Light/Cotton)', priceMinor: 5000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-w18', name: 'Women Saree (Silk Light)', priceMinor: 6000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-w19', name: 'Women Saree (Silk Heavy)', priceMinor: 10000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-w20', name: 'Women Saree (Heavy/Embroidered)', priceMinor: 10000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-w21', name: 'Women Kanjivaram Saree', priceMinor: 10000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-w22', name: 'Women Dulhan saree', priceMinor: 15000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-w23', name: 'Women Saree Banarasi (Light)', priceMinor: 6000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-w24', name: 'Women Saree Banarasi (Heavy)', priceMinor: 10000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-w25', name: 'Women Dupatta (Light)', priceMinor: 3000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-w26', name: 'Women Dupatta (Heavy)', priceMinor: 9000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-w27', name: 'Women Blouse (Light)', priceMinor: 3000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-w28', name: 'Women Blouse (Heavy)', priceMinor: 9000, priceType: 'fixed', unit: 'piece' },

  // Women Bottom
  { id: 'sp-wb1', name: 'Women Pant', priceMinor: 1800, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-wb2', name: 'Women Jeans', priceMinor: 1800, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-wb3', name: 'Women Trousers', priceMinor: 1800, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-wb4', name: 'Women Cargo Pants', priceMinor: 1800, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-wb5', name: 'Women Pyjama (Light)', priceMinor: 1800, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-wb6', name: 'Women Pyjama (Heavy/Embroidered)', priceMinor: 3000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-wb7', name: 'Women Chudidar (Light)', priceMinor: 3000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-wb8', name: 'Women Chudidar (Heavy)', priceMinor: 5000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-wb9', name: 'Women Lower', priceMinor: 1800, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-wb10', name: 'Women Half pant / Shorts', priceMinor: 1800, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-wb11', name: 'Women Sharara (Light)', priceMinor: 3000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-wb12', name: 'Women Sharara (Heavy)', priceMinor: 9000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-wb13', name: 'Women Lehenga (Light)', priceMinor: 10000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-wb14', name: 'Women Lehenga (Heavy)', priceMinor: 20000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-wb15', name: 'Women Lehenga (Heavy Cane)', priceMinor: 25000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-wb16', name: 'Women Skirt (Light)', priceMinor: 3000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-wb17', name: 'Women Skirt (Heavy)', priceMinor: 9000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-wb18', name: 'Women Palazzo (Light)', priceMinor: 3000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-wb19', name: 'Women Palazzo (Heavy)', priceMinor: 9000, priceType: 'fixed', unit: 'piece' },

  // Dress
  { id: 'sp-d1', name: 'Western One piece (Light)', priceMinor: 9000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-d2', name: 'Western one piece (Heavy)', priceMinor: 18000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-d3', name: 'Gown (Light)', priceMinor: 6000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-d4', name: 'Gown (Heavy)', priceMinor: 15000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-d5', name: 'Jumpsuit', priceMinor: 10000, priceType: 'fixed', unit: 'piece' },
  { id: 'sp-d6', name: 'Co-ord set (Light)', priceMinor: 6000, priceType: 'fixed', unit: 'set' },
  { id: 'sp-d7', name: 'Co-ord set (Heavy)', priceMinor: 15000, priceType: 'fixed', unit: 'set' }
];

export const MOCK_HOUSEHOLD = MOCK_DRY_CLEANING.filter(item => item.id.startsWith('dc-h'));
export const MOCK_LAUNDRY = [
  { id: 'l-1', name: 'Shirt', priceMinor: 9000, priceType: 'fixed', unit: 'piece' },
  { id: 'l-2', name: 'T-Shirt', priceMinor: 7000, priceType: 'fixed', unit: 'piece' },
  { id: 'l-3', name: 'Trousers', priceMinor: 11000, priceType: 'fixed', unit: 'piece' },
  { id: 'l-4', name: 'Jeans', priceMinor: 12000, priceType: 'fixed', unit: 'piece' }
];
export const MOCK_LUXURY_CARE = [
  { id: 'x-1', name: 'Designer Bag', priceMinor: 120000, priceMaxMinor: 250000, priceType: 'variable', unit: 'piece' },
  { id: 'x-2', name: 'Leather Jacket', priceMinor: 95000, priceType: 'fixed', unit: 'piece' }
];
