/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedZonesRouteImport } from './routes/_authenticated/zones'
import { Route as AuthenticatedWinbackRouteImport } from './routes/_authenticated/winback'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSlaBreachRouteImport } from './routes/_authenticated/sla-breach'
import { Route as AuthenticatedSettlementRouteImport } from './routes/_authenticated/settlement'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedScorecardsRouteImport } from './routes/_authenticated/scorecards'
import { Route as AuthenticatedSchedulerRouteImport } from './routes/_authenticated/scheduler'
import { Route as AuthenticatedRouteSheetRouteImport } from './routes/_authenticated/route-sheet'
import { Route as AuthenticatedReferralsRouteImport } from './routes/_authenticated/referrals'
import { Route as AuthenticatedReattemptsRouteImport } from './routes/_authenticated/reattempts'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedLabelsRouteImport } from './routes/_authenticated/labels'
import { Route as AuthenticatedKanbanRouteImport } from './routes/_authenticated/kanban'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedImportsRouteImport } from './routes/_authenticated/imports'
import { Route as AuthenticatedHeatmapRouteImport } from './routes/_authenticated/heatmap'
import { Route as AuthenticatedFeedbackRouteImport } from './routes/_authenticated/feedback'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedDriversRouteImport } from './routes/_authenticated/drivers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedCouponsRouteImport } from './routes/_authenticated/coupons'
import { Route as AuthenticatedComplaintsRouteImport } from './routes/_authenticated/complaints'
import { Route as AuthenticatedCatalogRouteImport } from './routes/_authenticated/catalog'
import { Route as AuthenticatedBroadcastsRouteImport } from './routes/_authenticated/broadcasts'
import { Route as AuthenticatedBannersRouteImport } from './routes/_authenticated/banners'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAppConfigRouteImport } from './routes/_authenticated/app-config'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAdminsRouteImport } from './routes/_authenticated/admins'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedZonesRoute = AuthenticatedZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWinbackRoute = AuthenticatedWinbackRouteImport.update({
  id: '/winback',
  path: '/winback',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSlaBreachRoute = AuthenticatedSlaBreachRouteImport.update({
  id: '/sla-breach',
  path: '/sla-breach',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettlementRoute = AuthenticatedSettlementRouteImport.update({
  id: '/settlement',
  path: '/settlement',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScorecardsRoute = AuthenticatedScorecardsRouteImport.update({
  id: '/scorecards',
  path: '/scorecards',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSchedulerRoute = AuthenticatedSchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRouteSheetRoute = AuthenticatedRouteSheetRouteImport.update({
  id: '/route-sheet',
  path: '/route-sheet',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReferralsRoute = AuthenticatedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReattemptsRoute = AuthenticatedReattemptsRouteImport.update({
  id: '/reattempts',
  path: '/reattempts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLabelsRoute = AuthenticatedLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKanbanRoute = AuthenticatedKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedImportsRoute = AuthenticatedImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHeatmapRoute = AuthenticatedHeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeedbackRoute = AuthenticatedFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDriversRoute = AuthenticatedDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCouponsRoute = AuthenticatedCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComplaintsRoute = AuthenticatedComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCatalogRoute = AuthenticatedCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBroadcastsRoute = AuthenticatedBroadcastsRouteImport.update({
  id: '/broadcasts',
  path: '/broadcasts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBannersRoute = AuthenticatedBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppConfigRoute = AuthenticatedAppConfigRouteImport.update({
  id: '/app-config',
  path: '/app-config',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminsRoute = AuthenticatedAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admins': typeof AuthenticatedAdminsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/app-config': typeof AuthenticatedAppConfigRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/banners': typeof AuthenticatedBannersRoute
  '/broadcasts': typeof AuthenticatedBroadcastsRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/complaints': typeof AuthenticatedComplaintsRoute
  '/coupons': typeof AuthenticatedCouponsRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/drivers': typeof AuthenticatedDriversRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/heatmap': typeof AuthenticatedHeatmapRoute
  '/imports': typeof AuthenticatedImportsRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/labels': typeof AuthenticatedLabelsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/reattempts': typeof AuthenticatedReattemptsRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/route-sheet': typeof AuthenticatedRouteSheetRoute
  '/scheduler': typeof AuthenticatedSchedulerRoute
  '/scorecards': typeof AuthenticatedScorecardsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/settlement': typeof AuthenticatedSettlementRoute
  '/sla-breach': typeof AuthenticatedSlaBreachRoute
  '/users': typeof AuthenticatedUsersRoute
  '/winback': typeof AuthenticatedWinbackRoute
  '/zones': typeof AuthenticatedZonesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admins': typeof AuthenticatedAdminsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/app-config': typeof AuthenticatedAppConfigRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/banners': typeof AuthenticatedBannersRoute
  '/broadcasts': typeof AuthenticatedBroadcastsRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/complaints': typeof AuthenticatedComplaintsRoute
  '/coupons': typeof AuthenticatedCouponsRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/drivers': typeof AuthenticatedDriversRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/heatmap': typeof AuthenticatedHeatmapRoute
  '/imports': typeof AuthenticatedImportsRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/labels': typeof AuthenticatedLabelsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/reattempts': typeof AuthenticatedReattemptsRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/route-sheet': typeof AuthenticatedRouteSheetRoute
  '/scheduler': typeof AuthenticatedSchedulerRoute
  '/scorecards': typeof AuthenticatedScorecardsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/settlement': typeof AuthenticatedSettlementRoute
  '/sla-breach': typeof AuthenticatedSlaBreachRoute
  '/users': typeof AuthenticatedUsersRoute
  '/winback': typeof AuthenticatedWinbackRoute
  '/zones': typeof AuthenticatedZonesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admins': typeof AuthenticatedAdminsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/app-config': typeof AuthenticatedAppConfigRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/banners': typeof AuthenticatedBannersRoute
  '/_authenticated/broadcasts': typeof AuthenticatedBroadcastsRoute
  '/_authenticated/catalog': typeof AuthenticatedCatalogRoute
  '/_authenticated/complaints': typeof AuthenticatedComplaintsRoute
  '/_authenticated/coupons': typeof AuthenticatedCouponsRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/drivers': typeof AuthenticatedDriversRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/feedback': typeof AuthenticatedFeedbackRoute
  '/_authenticated/heatmap': typeof AuthenticatedHeatmapRoute
  '/_authenticated/imports': typeof AuthenticatedImportsRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/kanban': typeof AuthenticatedKanbanRoute
  '/_authenticated/labels': typeof AuthenticatedLabelsRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/reattempts': typeof AuthenticatedReattemptsRoute
  '/_authenticated/referrals': typeof AuthenticatedReferralsRoute
  '/_authenticated/route-sheet': typeof AuthenticatedRouteSheetRoute
  '/_authenticated/scheduler': typeof AuthenticatedSchedulerRoute
  '/_authenticated/scorecards': typeof AuthenticatedScorecardsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/settlement': typeof AuthenticatedSettlementRoute
  '/_authenticated/sla-breach': typeof AuthenticatedSlaBreachRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/winback': typeof AuthenticatedWinbackRoute
  '/_authenticated/zones': typeof AuthenticatedZonesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admins'
    | '/analytics'
    | '/app-config'
    | '/audit'
    | '/banners'
    | '/broadcasts'
    | '/catalog'
    | '/complaints'
    | '/coupons'
    | '/crm'
    | '/dashboard'
    | '/drivers'
    | '/expenses'
    | '/feedback'
    | '/heatmap'
    | '/imports'
    | '/inbox'
    | '/kanban'
    | '/labels'
    | '/orders'
    | '/reattempts'
    | '/referrals'
    | '/route-sheet'
    | '/scheduler'
    | '/scorecards'
    | '/settings'
    | '/settlement'
    | '/sla-breach'
    | '/users'
    | '/winback'
    | '/zones'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admins'
    | '/analytics'
    | '/app-config'
    | '/audit'
    | '/banners'
    | '/broadcasts'
    | '/catalog'
    | '/complaints'
    | '/coupons'
    | '/crm'
    | '/dashboard'
    | '/drivers'
    | '/expenses'
    | '/feedback'
    | '/heatmap'
    | '/imports'
    | '/inbox'
    | '/kanban'
    | '/labels'
    | '/orders'
    | '/reattempts'
    | '/referrals'
    | '/route-sheet'
    | '/scheduler'
    | '/scorecards'
    | '/settings'
    | '/settlement'
    | '/sla-breach'
    | '/users'
    | '/winback'
    | '/zones'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admins'
    | '/_authenticated/analytics'
    | '/_authenticated/app-config'
    | '/_authenticated/audit'
    | '/_authenticated/banners'
    | '/_authenticated/broadcasts'
    | '/_authenticated/catalog'
    | '/_authenticated/complaints'
    | '/_authenticated/coupons'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/drivers'
    | '/_authenticated/expenses'
    | '/_authenticated/feedback'
    | '/_authenticated/heatmap'
    | '/_authenticated/imports'
    | '/_authenticated/inbox'
    | '/_authenticated/kanban'
    | '/_authenticated/labels'
    | '/_authenticated/orders'
    | '/_authenticated/reattempts'
    | '/_authenticated/referrals'
    | '/_authenticated/route-sheet'
    | '/_authenticated/scheduler'
    | '/_authenticated/scorecards'
    | '/_authenticated/settings'
    | '/_authenticated/settlement'
    | '/_authenticated/sla-breach'
    | '/_authenticated/users'
    | '/_authenticated/winback'
    | '/_authenticated/zones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/zones': {
      id: '/_authenticated/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof AuthenticatedZonesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/winback': {
      id: '/_authenticated/winback'
      path: '/winback'
      fullPath: '/winback'
      preLoaderRoute: typeof AuthenticatedWinbackRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sla-breach': {
      id: '/_authenticated/sla-breach'
      path: '/sla-breach'
      fullPath: '/sla-breach'
      preLoaderRoute: typeof AuthenticatedSlaBreachRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settlement': {
      id: '/_authenticated/settlement'
      path: '/settlement'
      fullPath: '/settlement'
      preLoaderRoute: typeof AuthenticatedSettlementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scorecards': {
      id: '/_authenticated/scorecards'
      path: '/scorecards'
      fullPath: '/scorecards'
      preLoaderRoute: typeof AuthenticatedScorecardsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scheduler': {
      id: '/_authenticated/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof AuthenticatedSchedulerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/route-sheet': {
      id: '/_authenticated/route-sheet'
      path: '/route-sheet'
      fullPath: '/route-sheet'
      preLoaderRoute: typeof AuthenticatedRouteSheetRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/referrals': {
      id: '/_authenticated/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedReferralsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reattempts': {
      id: '/_authenticated/reattempts'
      path: '/reattempts'
      fullPath: '/reattempts'
      preLoaderRoute: typeof AuthenticatedReattemptsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/labels': {
      id: '/_authenticated/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof AuthenticatedLabelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kanban': {
      id: '/_authenticated/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthenticatedKanbanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/imports': {
      id: '/_authenticated/imports'
      path: '/imports'
      fullPath: '/imports'
      preLoaderRoute: typeof AuthenticatedImportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/heatmap': {
      id: '/_authenticated/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof AuthenticatedHeatmapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feedback': {
      id: '/_authenticated/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthenticatedFeedbackRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/drivers': {
      id: '/_authenticated/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof AuthenticatedDriversRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coupons': {
      id: '/_authenticated/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof AuthenticatedCouponsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/complaints': {
      id: '/_authenticated/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof AuthenticatedComplaintsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog': {
      id: '/_authenticated/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthenticatedCatalogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/broadcasts': {
      id: '/_authenticated/broadcasts'
      path: '/broadcasts'
      fullPath: '/broadcasts'
      preLoaderRoute: typeof AuthenticatedBroadcastsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/banners': {
      id: '/_authenticated/banners'
      path: '/banners'
      fullPath: '/banners'
      preLoaderRoute: typeof AuthenticatedBannersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app-config': {
      id: '/_authenticated/app-config'
      path: '/app-config'
      fullPath: '/app-config'
      preLoaderRoute: typeof AuthenticatedAppConfigRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admins': {
      id: '/_authenticated/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AuthenticatedAdminsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminsRoute: typeof AuthenticatedAdminsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAppConfigRoute: typeof AuthenticatedAppConfigRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBannersRoute: typeof AuthenticatedBannersRoute
  AuthenticatedBroadcastsRoute: typeof AuthenticatedBroadcastsRoute
  AuthenticatedCatalogRoute: typeof AuthenticatedCatalogRoute
  AuthenticatedComplaintsRoute: typeof AuthenticatedComplaintsRoute
  AuthenticatedCouponsRoute: typeof AuthenticatedCouponsRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDriversRoute: typeof AuthenticatedDriversRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedFeedbackRoute: typeof AuthenticatedFeedbackRoute
  AuthenticatedHeatmapRoute: typeof AuthenticatedHeatmapRoute
  AuthenticatedImportsRoute: typeof AuthenticatedImportsRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedKanbanRoute: typeof AuthenticatedKanbanRoute
  AuthenticatedLabelsRoute: typeof AuthenticatedLabelsRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedReattemptsRoute: typeof AuthenticatedReattemptsRoute
  AuthenticatedReferralsRoute: typeof AuthenticatedReferralsRoute
  AuthenticatedRouteSheetRoute: typeof AuthenticatedRouteSheetRoute
  AuthenticatedSchedulerRoute: typeof AuthenticatedSchedulerRoute
  AuthenticatedScorecardsRoute: typeof AuthenticatedScorecardsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSettlementRoute: typeof AuthenticatedSettlementRoute
  AuthenticatedSlaBreachRoute: typeof AuthenticatedSlaBreachRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedWinbackRoute: typeof AuthenticatedWinbackRoute
  AuthenticatedZonesRoute: typeof AuthenticatedZonesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminsRoute: AuthenticatedAdminsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAppConfigRoute: AuthenticatedAppConfigRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBannersRoute: AuthenticatedBannersRoute,
  AuthenticatedBroadcastsRoute: AuthenticatedBroadcastsRoute,
  AuthenticatedCatalogRoute: AuthenticatedCatalogRoute,
  AuthenticatedComplaintsRoute: AuthenticatedComplaintsRoute,
  AuthenticatedCouponsRoute: AuthenticatedCouponsRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDriversRoute: AuthenticatedDriversRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedFeedbackRoute: AuthenticatedFeedbackRoute,
  AuthenticatedHeatmapRoute: AuthenticatedHeatmapRoute,
  AuthenticatedImportsRoute: AuthenticatedImportsRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedKanbanRoute: AuthenticatedKanbanRoute,
  AuthenticatedLabelsRoute: AuthenticatedLabelsRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedReattemptsRoute: AuthenticatedReattemptsRoute,
  AuthenticatedReferralsRoute: AuthenticatedReferralsRoute,
  AuthenticatedRouteSheetRoute: AuthenticatedRouteSheetRoute,
  AuthenticatedSchedulerRoute: AuthenticatedSchedulerRoute,
  AuthenticatedScorecardsRoute: AuthenticatedScorecardsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSettlementRoute: AuthenticatedSettlementRoute,
  AuthenticatedSlaBreachRoute: AuthenticatedSlaBreachRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedWinbackRoute: AuthenticatedWinbackRoute,
  AuthenticatedZonesRoute: AuthenticatedZonesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
